openapi: 3.0.3
info:
  description: API de Netflux realizada por el grupo 3 de la asignatura ASEE. Microservicio
    de **Visualizaciones y Recomendaciones**.
  license:
    name: Copyleft
    url: https://url/a/la/licencia
  title: Netflux Grupo 3 - OpenAPI 3.0
  version: 0.0.1
servers:
- url: https://path/api/v1
tags:
- description: Datos sobre las visualizaciones
  name: Visualizacion
- description: Datos sobre las recomendaciones
  name: Recomendacion
paths:
  /usuarios/{usuarioId}/perfiles/{perfilId}/recomendaciones:
    delete:
      description: Elimina las recomendaciones de un perfil
      operationId: eliminar_recomendacion_perfil
      parameters:
      - description: ID del perfil especificado
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del usuario especificado
        explode: false
        in: path
        name: usuarioId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      responses:
        "204":
          description: Recomendaciones eliminadas correctamente
        "404":
          description: Perfil o usuario no encontrado
        "500":
          description: Error interno del servidor
      summary: Elimina todas las recomendaciones de un perfil
      tags:
      - Recomendacion
      x-openapi-router-controller: openapi_server.controllers.recomendacion_controller
    get:
      description: Obtiene una lista de las recomendaciones para el perfil
      operationId: obtener_recomendaciones_perfil
      parameters:
      - description: ID del perfil especificado
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Recomendacion'
                type: array
          description: Lista de recomendaciones obtenida correctamente
        "404":
          description: Perfil no encontrado
        "500":
          description: Error interno del servidor
      summary: Obtiene una lista de las recomendaciones para el perfil
      tags:
      - Recomendacion
      x-openapi-router-controller: openapi_server.controllers.recomendacion_controller
    patch:
      description: Actualiza las recomendaciones de un perfil
      operationId: actualizar_lista_recomendacion_perfil
      parameters:
      - description: ID del perfil especificado
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del usuario especificado
        explode: false
        in: path
        name: usuarioId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recomendacion'
        description: ID del contenido a visualizar
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recomendacion'
          description: Recomendaciones actualizadas correctamente
        "404":
          description: Perfil o recomendacion no encontrado
        "500":
          description: Error interno del servidor
      summary: Actualiza las recomendaciones de un perfil
      tags:
      - Recomendacion
      x-openapi-router-controller: openapi_server.controllers.recomendacion_controller
    post:
      description: Crea una recomendación para un perfil en específico
      operationId: crear_recomendacion_perfil
      parameters:
      - description: ID del perfil especificado
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recomendacion'
        description: ID del contenido a visualizar
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recomendacion'
          description: Recomendación creada correctamente
        "404":
          description: Perfil o recomendacion no encontrado
        "500":
          description: Error interno del servidor
      summary: Crea una recomendación para un perfil
      tags:
      - Recomendacion
      x-openapi-router-controller: openapi_server.controllers.recomendacion_controller
  # /perfil/{perfilId}/recomendaciones/{recomendacionId}:
  #   delete:
  #     description: Elimina una recomendación en específico de un perfil
  #     operationId: eliminar_recomendacion_perfil
  #     parameters:
  #     - description: ID del perfil especificado
  #       explode: false
  #       in: path
  #       name: perfilId
  #       required: true
  #       schema:
  #         example: 1
  #         format: int64
  #         type: integer
  #       style: simple
  #     - description: ID de la recomendacion especificada
  #       explode: false
  #       in: path
  #       name: recomendacionId
  #       required: true
  #       schema:
  #         example: 1
  #         format: int64
  #         type: integer
  #       style: simple
  #     responses:
  #       "204":
  #         description: Recomendación eliminada correctamente
  #       "404":
  #         description: Perfil o recomendacion no encontrado
  #       "500":
  #         description: Error interno del servidor
  #     summary: Elimina una recomendación en específico de un perfil
  #     tags:
  #     - Recomendacion
  #     x-openapi-router-controller: openapi_server.controllers.recomendacion_controller
  # /visualizacion/{contenidoId}:
  #   get:
  #     description: Lista de perfiles que han visto el contenido especificado.
  #     operationId: listar_visualizaciones_contenido
  #     parameters:
  #     - description: ID del perfil a obtener
  #       explode: false
  #       in: path
  #       name: contenidoId
  #       required: true
  #       schema:
  #         example: 1
  #         format: int64
  #         type: integer
  #       style: simple
  #     responses:
  #       "200":
  #         content:
  #           application/json:
  #             schema:
  #               items:
  #                 $ref: '#/components/schemas/Perfil'
  #               type: array
  #         description: Lista de visualizaciones obtenida exitosamente
  #       "404":
  #         description: Perfil no encontrado
  #       "500":
  #         description: Error interno del servidor
  #     summary: Lista de perfiles que han visto el contenido especificado
  #     tags:
  #     - Visualizacion
  #     x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
  /usuarios/{userId}/perfiles/{perfilId}/visualizaciones:
    delete:
      description: Elimina todas las visualizaciones de un perfil
      operationId: borrar_visualizaciones_perfil
      parameters:
      - description: ID del perfil especificado
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del usuario especificado
        explode: false
        in: path
        name: userId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      responses:
        "204":
          description: Visualizaciones eliminadas correctamente
        "404":
          description: Perfil o usuario no encontrado
        "500":
          description: Error interno del servidor
      summary: Elimina todas las visualizaciones de un perfil
      tags:
      - Visualizacion
      x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
    get:
      description: Obtiene una lista de todos los capítulos o películas visualizados
        o en progreso por el perfil especificado.
      operationId: listar_visualizaciones_perfil
      parameters:
      - description: ID del perfil a obtener
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Visualizacion'
                type: array
          description: Lista de visualizaciones obtenida exitosamente
        "404":
          description: Perfil no encontrado
        "500":
          description: Error interno del servidor
      summary: Historial de un perfil en específico
      tags:
      - Visualizacion
      x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
    post:
      description: Inicia la visualización de un capítulo o película por un perfil
      operationId: crear_visualizacion_contenido_perfil
      parameters:
      - description: ID del perfil especificado
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Visualizacion'
        description: ID del contenido a visualizar
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Visualizacion'
          description: Visualización creada exitosamente
        "404":
          description: Perfil no encontrado
        "500":
          description: Error interno del servidor
      summary: Inicia la visualización de un capítulo o película por un perfil
      tags:
      - Visualizacion
      x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
  /usuarios/{userId}/perfiles/{perfilId}/visualizaciones/{contenidoId}:
    delete:
      description: Elimina una visualización en específico de un perfil
      operationId: borrar_visualizacion_perfil
      parameters:
      - description: ID del perfil especificado
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del contenido a eliminar
        explode: false
        in: path
        name: contenidoId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del usuario especificado
        explode: false
        in: path
        name: userId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      responses:
        "204":
          description: Visualización eliminada correctamente
        "404":
          description: Perfil o visualización no encontrada
        "500":
          description: Error interno del servidor
      summary: Elimina una visualización en específico de un perfil
      tags:
      - Visualizacion
      x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
    patch:
      description: Actualiza la visualización de un capítulo o película por un perfil
      operationId: actualizar_visualizacion_contenido_perfil
      parameters:
      - description: ID del perfil especificado
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del contenido a visualizar
        explode: false
        in: path
        name: contenidoId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del usuario especificado
        explode: false
        in: path
        name: userId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Visualizacion'
        description: ID del contenido a visualizar
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Visualizacion'
          description: Visualización actualizada exitosamente
        "404":
          description: Perfil o visualización no encontrada
        "500":
          description: Error interno del servidor
      summary: Actualiza la visualización de un capítulo o película por un perfil
      tags:
      - Visualizacion
      x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
  /usuarios/{userId}/perfiles/{perfilId}/visualizaciones/capitulos/{capituloId}:
    get:
      description: Obtiene el capítulo en visualización por el perfil especificado.
      operationId: obtener_visualizacion_capitulo_perfil
      parameters:
      - description: ID del perfil a obtener
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del capitulo a obtener
        explode: false
        in: path
        name: capituloId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del usuario especificado
        explode: false
        in: path
        name: userId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Capitulo'
          description: Capítulo obtenido correctamente
        "404":
          description: Perfil o contenido no encontrado
        "500":
          description: Error interno del servidor
      summary: Obtiene el capítulo en visualización del perfil especificado
      tags:
      - Visualizacion
      x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
  /usuarios/{userId}/perfiles/{perfilId}/visualizaciones/peliculas/{peliculaId}:
    get:
      description: Obtiene la película en visualización por el perfil especificado.
      operationId: obtener_visualizacion_pelicula_perfil
      parameters:
      - description: ID del perfil a obtener
        explode: false
        in: path
        name: perfilId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID de la película a obtener
        explode: false
        in: path
        name: peliculaId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      - description: ID del usuario especificado
        explode: false
        in: path
        name: userId
        required: true
        schema:
          example: 1
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pelicula'
          description: Película obtenida correctamente
        "404":
          description: Perfil o contenido no encontrado
        "500":
          description: Error interno del servidor
      summary: Obtiene la película visualizada por el perfil especificado
      tags:
      - Visualizacion
      x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
  # /visualizacion/{perfilId}/{capituloId}:
  #   get:
  #     description: Obtiene el capítulo en visualización por el perfil especificado.
  #     operationId: obtener_visualizacion_capitulo_perfil
  #     parameters:
  #     - description: ID del perfil a obtener
  #       explode: false
  #       in: path
  #       name: perfilId
  #       required: true
  #       schema:
  #         example: 1
  #         format: int64
  #         type: integer
  #       style: simple
  #     - description: ID del perfil a obtener
  #       explode: false
  #       in: path
  #       name: capituloId
  #       required: true
  #       schema:
  #         example: 1
  #         format: int64
  #         type: integer
  #       style: simple
  #     responses:
  #       "200":
  #         content:
  #           application/json:
  #             schema:
  #               items:
  #                 $ref: '#/components/schemas/Capitulo'
  #               type: array
  #         description: Capítulo obtenido correctamente
  #       "404":
  #         description: Perfil o contenido no encontrado
  #       "500":
  #         description: Error interno del servidor
  #     summary: Obtiene el capítulo en visualización del perfil especificado
  #     tags:
  #     - Visualizacion
  #     x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
  # /visualizacion/{perfilId}/{peliculaId}:
  #   get:
  #     description: Obtiene la película en visualización por el perfil especificado.
  #     operationId: obtener_visualizacion_pelicula_perfil
  #     parameters:
  #     - description: ID del perfil a obtener
  #       explode: false
  #       in: path
  #       name: perfilId
  #       required: true
  #       schema:
  #         example: 1
  #         format: int64
  #         type: integer
  #       style: simple
  #     - description: ID del perfil a obtener
  #       explode: false
  #       in: path
  #       name: peliculaId
  #       required: true
  #       schema:
  #         example: 1
  #         format: int64
  #         type: integer
  #       style: simple
  #     responses:
  #       "200":
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Pelicula'
  #         description: Película obtenida correctamente
  #       "404":
  #         description: Perfil o contenido no encontrado
  #       "500":
  #         description: Error interno del servidor
  #     summary: Obtiene la película visualizada por el perfil especificado
  #     tags:
  #     - Visualizacion
  #     x-openapi-router-controller: openapi_server.controllers.visualizacion_controller
components:
  schemas:
    Visualizacion:
      example:
        fecha_visualizacion: 2002-12-14
        id_perfil: 1
        id_contenido: 1
        progreso: 20
      properties:
        id_perfil:
          example: 1
          format: int64
          title: id_perfil
          type: integer
        id_contenido:
          example: 1
          format: int64
          title: id_contenido
          type: integer
        fecha_visualizacion:
          example: 2002-12-14
          format: date
          title: fecha_visualizacion
          type: string
        progreso:
          description: "El porcentaje visualizado de un capítulo. Mínimo 0, máximo\
            \ 100"
          example: 20
          format: int32
          title: progreso
          type: integer
      title: Visualizacion
      type: object
    Recomendacion:
      example:
        contenido_recomendado:
        - numero: 1
          titulo: Piloto
          duracion: 58
          id: 1
          sinopsis: Walter White toma una decisión radical tras ser diagnosticado
            con cáncer de pulmón.
        - numero: 1
          titulo: Piloto
          duracion: 58
          id: 1
          sinopsis: Walter White toma una decisión radical tras ser diagnosticado
            con cáncer de pulmón.
        id_recomendacion: 1
        id_perfil: 1
      properties:
        id_recomendacion:
          example: 1
          format: int64
          title: id_recomendacion
          type: integer
        id_perfil:
          example: 1
          format: int64
          title: id_perfil
          type: integer
        contenido_recomendado:
          items:
            $ref: '#/components/schemas/Capitulo'
          title: contenido_recomendado
          type: array
      title: Recomendacion
      type: object
    Perfil:
      example:
        user_id: 3
        preferencias_contenido:
          languages:
          - Espanol
          genres:
          - Action
          - Supernatural
        foto_perfil: path/to/image
        id: 1
        nombre: Euler
        historial_vistos:
        - numero: 1
          titulo: Piloto
          duracion: 58
          id: 1
          sinopsis: Walter White toma una decisión radical tras ser diagnosticado
            con cáncer de pulmón.
        - numero: 1
          titulo: Piloto
          duracion: 58
          id: 1
          sinopsis: Walter White toma una decisión radical tras ser diagnosticado
            con cáncer de pulmón.
        mi_lista:
        - numero: 1
          titulo: Piloto
          duracion: 58
          id: 1
          sinopsis: Walter White toma una decisión radical tras ser diagnosticado
            con cáncer de pulmón.
        - numero: 1
          titulo: Piloto
          duracion: 58
          id: 1
          sinopsis: Walter White toma una decisión radical tras ser diagnosticado
            con cáncer de pulmón.
      properties:
        id:
          description: ID del perfil en específico
          example: 1
          format: int64
          title: id
          type: integer
        user_id:
          description: ID del usuario al que pertenece el perfil
          example: 3
          format: int64
          title: user_id
          type: integer
        nombre:
          example: Euler
          title: nombre
          type: string
        foto_perfil:
          example: path/to/image
          title: foto_perfil
          type: string
        historial_vistos:
          items:
            $ref: '#/components/schemas/Capitulo'
          title: historial_vistos
          type: array
        mi_lista:
          description: Lista con el contenido que el usuario ha guardado
          items:
            $ref: '#/components/schemas/Capitulo'
          title: mi_lista
          type: array
        preferencias_contenido:
          $ref: '#/components/schemas/Perfil_preferencias_contenido'
      required:
      - nombre
      title: Perfil
      type: object
    Serie:
      properties:
        id:
          example: 1
          format: int64
          type: integer
        titulo:
          example: Breaking Bad
          type: string
        genero:
          example: Drama
          type: string
        sinopsis:
          example: Un profesor de química se convierte en fabricante de metanfetamina.
          type: string
        anioEstreno:
          example: 2008
          format: int32
          type: integer
        temporadas:
          items:
            $ref: '#/components/schemas/Temporada'
          type: array
        actores:
          items:
            $ref: '#/components/schemas/Actor'
          type: array
      required:
      - anioEstreno
      - genero
      - sinopsis
      - titulo
      type: object
      xml:
        name: serie
    Temporada:
      example:
        capitulos:
        - numero: 1
          titulo: Piloto
          duracion: 58
          id: 1
          sinopsis: Walter White toma una decisión radical tras ser diagnosticado
            con cáncer de pulmón.
        - numero: 1
          titulo: Piloto
          duracion: 58
          id: 1
          sinopsis: Walter White toma una decisión radical tras ser diagnosticado
            con cáncer de pulmón.
        numero: 1
        anioLanzamiento: 2008
        id: 1
      properties:
        id:
          example: 1
          format: int64
          title: id
          type: integer
        numero:
          example: 1
          format: int32
          title: numero
          type: integer
        anioLanzamiento:
          example: 2008
          format: int32
          title: anioLanzamiento
          type: integer
        capitulos:
          items:
            $ref: '#/components/schemas/Capitulo'
          title: capitulos
          type: array
      required:
      - anioLanzamiento
      - numero
      title: Temporada
      type: object
      xml:
        name: temporada
    Capitulo:
      example:
        numero: 1
        titulo: Piloto
        duracion: 58
        id: 1
        sinopsis: Walter White toma una decisión radical tras ser diagnosticado con
          cáncer de pulmón.
      properties:
        id:
          example: 1
          format: int64
          title: id
          type: integer
        numero:
          example: 1
          format: int32
          title: numero
          type: integer
        titulo:
          example: Piloto
          title: titulo
          type: string
        duracion:
          description: Duración del capítulo en minutos
          example: 58
          format: int32
          title: duracion
          type: integer
        sinopsis:
          example: Walter White toma una decisión radical tras ser diagnosticado con
            cáncer de pulmón.
          title: sinopsis
          type: string
      required:
      - duracion
      - numero
      - titulo
      title: Capitulo
      type: object
      xml:
        name: capitulo
    Pelicula:
      example:
        actores:
        - fechaNacimiento: 1956-03-07
          biografia: Actor estadounidense conocido por su papel en 'Breaking Bad'.
          id: 1
          nombre: Bryan Cranston
          personaje: Walter White
        - fechaNacimiento: 1956-03-07
          biografia: Actor estadounidense conocido por su papel en 'Breaking Bad'.
          id: 1
          nombre: Bryan Cranston
          personaje: Walter White
        temporadas:
        - capitulos:
          - numero: 1
            titulo: Piloto
            duracion: 58
            id: 1
            sinopsis: Walter White toma una decisión radical tras ser diagnosticado
              con cáncer de pulmón.
          - numero: 1
            titulo: Piloto
            duracion: 58
            id: 1
            sinopsis: Walter White toma una decisión radical tras ser diagnosticado
              con cáncer de pulmón.
          numero: 1
          anioLanzamiento: 2008
          id: 1
        - capitulos:
          - numero: 1
            titulo: Piloto
            duracion: 58
            id: 1
            sinopsis: Walter White toma una decisión radical tras ser diagnosticado
              con cáncer de pulmón.
          - numero: 1
            titulo: Piloto
            duracion: 58
            id: 1
            sinopsis: Walter White toma una decisión radical tras ser diagnosticado
              con cáncer de pulmón.
          numero: 1
          anioLanzamiento: 2008
          id: 1
        genero: Drama
        titulo: Breaking Bad
        duracion: 112
        anioEstreno: 2008
        id: 1
        sinopsis: Un profesor de química se convierte en fabricante de metanfetamina.
      properties:
        id:
          example: 1
          format: int64
          title: id
          type: integer
        titulo:
          example: Breaking Bad
          title: titulo
          type: string
        genero:
          example: Drama
          title: genero
          type: string
        sinopsis:
          example: Un profesor de química se convierte en fabricante de metanfetamina.
          title: sinopsis
          type: string
        anioEstreno:
          example: 2008
          format: int32
          title: anioEstreno
          type: integer
        duracion:
          example: 112
          format: int32
          title: duracion
          type: integer
        temporadas:
          items:
            $ref: '#/components/schemas/Temporada'
          title: temporadas
          type: array
        actores:
          items:
            $ref: '#/components/schemas/Actor'
          title: actores
          type: array
      required:
      - anioEstreno
      - genero
      - sinopsis
      - titulo
      title: Pelicula
      type: object
      xml:
        name: serie
    Actor:
      example:
        fechaNacimiento: 1956-03-07
        biografia: Actor estadounidense conocido por su papel en 'Breaking Bad'.
        id: 1
        nombre: Bryan Cranston
        personaje: Walter White
      properties:
        id:
          example: 1
          format: int64
          title: id
          type: integer
        nombre:
          example: Bryan Cranston
          title: nombre
          type: string
        fechaNacimiento:
          example: 1956-03-07
          format: date
          title: fechaNacimiento
          type: string
        personaje:
          example: Walter White
          title: personaje
          type: string
        biografia:
          example: Actor estadounidense conocido por su papel en 'Breaking Bad'.
          title: biografia
          type: string
      required:
      - nombre
      - personaje
      title: Actor
      type: object
      xml:
        name: actor
    Perfil_preferencias_contenido:
      description: Preferencias de contenido del usuario
      example:
        languages:
        - Espanol
        genres:
        - Action
        - Supernatural
      properties:
        genres:
          example:
          - Action
          - Supernatural
          items:
            type: string
          title: genres
          type: array
        languages:
          example:
          - Espanol
          items:
            enum:
            - Ingles
            - Espanol
            type: string
          title: languages
          type: array
      title: Perfil_preferencias_contenido
      type: object
